version: "3"
services:
  api:
    container_name: nekoringo-api
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/nekoringo-api
    links:
      - redis
      - db
      - bitgo
  db:
    image: "mariadb:10.1.30"
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "nekoringo"
    ports:
      - "3306:3306"
